### ISSUE TITLE
Error on EMS

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/monitoring#12]
The deployment of [this app](https://development.ui.nebulous.eu.existanze.gr/applications) shows some errors in the EMS:

![image](https://github.com/eu-nebulous/monitoring/assets/172278014/19e8d8fc-14f2-4351-a04d-cb90a6426903)

EMS Server:

```
2024-07-03T14:45:44.981Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.981Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : ****      T R A N S L A T I O N   R E S U L T S      ****
2024-07-03T14:45:44.981Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.981Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Model Name: df4d9385-1a7a-4013-856e-ed35f68d0436
2024-07-03T14:45:44.982Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.982Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Event-to-Action map:
{}
2024-07-03T14:45:44.982Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.983Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : SLO set:
[combined_slo_1720017944087]
2024-07-03T14:45:44.983Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.983Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Component-to-Sensor map:
{Component::spec-comp=[PullSensor::cpu_utilisation_persist_SENSOR]}
2024-07-03T14:45:44.984Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.985Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Data-to-Sensor map:
{}
2024-07-03T14:45:44.986Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.986Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Monitors:
 [cpu_utilisation_persist_SENSOR]
2024-07-03T14:45:44.990Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.993Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Grouping-to-EPL Rules map:
-----------------------
PER_INSTANCE:
  cpu_utilisation_persist:
    - /* RAW-CTX-PER_INSTANCE */ /*INSERT INTO cpu_utilisation_persist*/
      SELECT * FROM cpu_utilisation_persist_SENSOR OUTPUT ALL EVERY 10 SECONDS
-----------------------
GLOBAL:
  combined_slo_1720017944087:
    - /* SLO-any */ /*INSERT INTO combined_slo_1720017944087*/
      SELECT * FROM combined_slo_1720017944087_CONSTRAINT
  combined_slo_1720017944087_CONSTRAINT:
    - /* CONSTR-MET-any */ /*INSERT INTO combined_slo_1720017944087_CONSTRAINT*/
      SELECT * FROM cpu_utilisation_persist HAVING cpu_utilisation_persist.metricValue < 50.0

2024-07-03T14:45:44.993Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.994Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Grouping-to-Topics map:
  PER_INSTANCE:
    - cpu_utilisation_persist
    - cpu_utilisation_persist_SENSOR
  GLOBAL:
    - cpu_utilisation_persist
    - combined_slo_1720017944087_CONSTRAINT
    - combined_slo_1720017944087
2024-07-03T14:45:44.994Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.995Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Topics-Connections map:
  PER_INSTANCE:
    cpu_utilisation_persist: [GLOBAL]
2024-07-03T14:45:44.995Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.996Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : MVV set:
[]
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : MVV_CP map:
{}
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : CMVAR set:
[]
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : RMVAR set:
[]
2024-07-03T14:45:44.997Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.998Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Function Definitions set:
[]
2024-07-03T14:45:44.998Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:44.998Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Metric Constraints:
[MetricConstraint(super=UnaryConstraint(super=Constraint(super=NamedElement(super=AbstractRootObject(_objectClass=gr.iccs.imu.ems.translate.model.MetricConstraint, object=null, container=null), name=combined_slo_1720017944087_CONSTRAINT, description=null, annotations=null)), validity=null, comparisonOperator=LESS_THAN, threshold=50.0), metricContext=null)]
2024-07-03T14:45:45.001Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.002Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Busy-Status Destination-to-Metric Context names map:
{}
2024-07-03T14:45:45.003Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Busy-Status Metrics:
[]
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Top-Level Metric names:
[combined_slo_1720017944087]
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Additional Results:
{NEBULOUS_PREDICTION_SLO_METRIC_DECOMPOSITION_MAP={name=df4d9385-1a7a-4013-856e-ed35f68d0436, constraints=[{metric=cpu_utilisation_persist, name=combined_slo_1720017944087_CONSTRAINT, operator=<, threshold=50.0}], version=0.0, operator=OR}, NEBULOUS_PREDICTION_SLO_METRIC_DECOMPOSITION={"name":"df4d9385-1a7a-4013-856e-ed35f68d0436","constraints":[{"metric":"cpu_utilisation_persist","name":"combined_slo_1720017944087_CONSTRAINT","operator":"<","threshold":50.0}],"version":0,"operator":"OR"}, NEBULOUS_PREDICTION_TOP_LEVEL_NODES_METRICS_MAP={metric_list=[{lower_bound=-Infinity, name=cpu_utilisation_persist, upper_bound=Infinity}], name=df4d9385-1a7a-4013-856e-ed35f68d0436, version=0}, NEBULOUS_PREDICTION_TOP_LEVEL_NODES_METRICS={"metric_list":[{"lower_bound":"-Infinity","name":"cpu_utilisation_persist","upper_bound":"Infinity"}],"name":"df4d9385-1a7a-4013-856e-ed35f68d0436","version":0}}
2024-07-03T14:45:45.014Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.015Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : Export files:
[]
2024-07-03T14:45:45.015Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.t.TranslationContextPrinter      : *********************************************************
2024-07-03T14:45:45.015Z  WARN 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): No App Exec model has been provided
2024-07-03T14:45:45.015Z  INFO 30 --- [ taskExecutor-1] g.iccs.imu.ems.brokercep.cep.CepService  : CepService: Clear registered Statements
2024-07-03T14:45:45.016Z  INFO 30 --- [ taskExecutor-1] g.iccs.imu.ems.brokercep.cep.CepService  : CepService: Clear registered Event Types
2024-07-03T14:45:45.070Z  INFO 30 --- [ taskExecutor-1] g.i.imu.ems.brokercep.BrokerCepService   : BrokerCepService.addEventTypes(): Adding event types: [cpu_utilisation_persist, combined_slo_1720017944087_CONSTRAINT, combined_slo_1720017944087]
2024-07-03T14:45:45.113Z  INFO 30 --- [ taskExecutor-1] g.i.imu.ems.brokercep.BrokerCepService   : BrokerCepService.setConstants(): Add/Set constants: {}
2024-07-03T14:45:45.113Z  INFO 30 --- [ taskExecutor-1] g.i.imu.ems.brokercep.BrokerCepService   : BrokerCepService.addFunctionDefinitions(): Adding function definitions: []
2024-07-03T14:45:45.460Z  INFO 30 --- [:1): I/O Thread] o.a.q.p.client.impl.ClientConnection     : Connection ID:7dbe9570-a973-41bc-a00b-20ea05df6776:3:1 connected to server: 158.37.63.86:32754
2024-07-03T14:45:46.210Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.setServerConfiguration(): stopping SSH server...
2024-07-03T14:45:46.211Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Stopping SSH server...
2024-07-03T14:45:46.239Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Stopped
2024-07-03T14:45:46.239Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.setServerConfiguration(): stopping SSH server... done
2024-07-03T14:45:46.244Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.c.c.ClusteringCoordinator    : Cluster Detector class: gr.iccs.imu.ems.baguette.server.coordinator.cluster.ClusterZoneDetector
2024-07-03T14:45:46.250Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.c.TwoLevelCoordinator        : TwoLevelCoordinator.initialize(): Groupings: top-level=GLOBAL, node-level=PER_INSTANCE
2024-07-03T14:45:46.250Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server...
2024-07-03T14:45:46.250Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : ** SSH server **
2024-07-03T14:45:46.250Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Public IP address: 10.0.4.244
2024-07-03T14:45:46.251Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:  Starting on port: 2222
2024-07-03T14:45:46.253Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:   Server key file: /opt/ems-server/config/hostkey.pem
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Ready
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.coordinator.NoopCoordinator  : TwoLevelCoordinator: start(): Invoking callback
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****************************************
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****  MONITORING TOPOLOGY IS READY  ****
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****************************************
2024-07-03T14:45:46.277Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server... done
2024-07-03T14:45:46.280Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.startNetdataCollector(): Starting NetdataCollector: app-model-id=df4d9385-1a7a-4013-856e-ed35f68d0436.yml
2024-07-03T14:45:46.280Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerNetdataCollector: Started
2024-07-03T14:45:46.280Z  WARN 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Skipping MetaSolver setup due to configuration
2024-07-03T14:45:46.281Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Cache translation results: app-model-id=df4d9385-1a7a-4013-856e-ed35f68d0436.yml
2024-07-03T14:45:46.281Z  WARN 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Skipping notification due to configuration
2024-07-03T14:45:46.281Z  INFO 30 --- [ taskExecutor-1] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Set applicationId to: df4d9385-1a7a-4013-856e-ed35f68d0436  -- was: df4d9385-1a7a-4013-856e-ed35f68d0436
2024-07-03T14:45:46.283Z  INFO 30 --- [ taskExecutor-1] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Start deploying EMS clients...
2024-07-03T14:45:46.286Z  INFO 30 --- [       Thread-7] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Started: period=60000ms
2024-07-03T14:45:46.307Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.NodeRegistrationCoordinator  : NodeRegistrationCoordinator.registerNode(): ExecutionWare: PROACTIVE
2024-07-03T14:45:46.308Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): END: app-model-id=df4d9385-1a7a-4013-856e-ed35f68d0436.yml
2024-07-03T14:45:46.309Z  INFO 30 --- [ taskExecutor-1] e.n.ems.service.EmsBootInitializer       : Metric model processing result: {ems-state-message=, ems-state-change-timestamp=1720017946309, ems-state=READY}
2024-07-03T14:45:46.310Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Executing Client installation Task #0: task-id=K8S-_-dummy-1720017946283-dummy-1720017946283-Kubernetes-_-_, node-id=dummy-1720017946283, name=dummy-1720017946283, type=K8S, address=unknown-address-1720017946306
2024-07-03T14:45:46.409Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Using K8sClientInstaller for task #0
2024-07-03T14:45:46.412Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Extra Env.Vars:

2024-07-03T14:45:47.460Z  WARN 30 --- [pool-4-thread-1] i.f.kubernetes.client.internal.SSLUtils  : SSL handshake failed. Falling back to insecure connection.
2024-07-03T14:46:35.236Z  INFO 30 --- [       Thread-6] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Stopped
2024-07-03T14:46:35.331Z  INFO 30 --- [   scheduling-1] g.iccs.imu.ems.control.util.TopicBeacon  : Topic Beacon: updateModelVersion: Model changed:  -> /df4d9385-1a7a-4013-856e-ed35f68d0436.yml, version: 1
2024-07-03T14:46:35.352Z  INFO 30 --- [       Thread-5] .i.i.e.b.b.i.MessageForwarderInterceptor : MessageQueueProcessor: Forward destinations initialized: []
2024-07-03T14:47:57.052Z ERROR 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Failed executing installation instructions for task #0, Exception:

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [patch]  for kind: [ConfigMap]  with name: [ems-client-configmap]  in namespace: [default]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:234)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:237)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:252)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1172)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:97)
        at gr.iccs.imu.ems.common.k8s.K8sClient.createConfigMap(K8sClient.java:102)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.createEmsClientConfigMap(K8sClientInstaller.java:163)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.deployOnCluster(K8sClientInstaller.java:140)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.deployOnCluster(K8sClientInstaller.java:134)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.executeTask(K8sClientInstaller.java:119)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstallerPlugin.execute(ClientInstallerPlugin.java:15)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.lambda$executeKubernetesTask$6(ClientInstaller.java:232)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeInstaller(ClientInstaller.java:180)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeKubernetesTask(ClientInstaller.java:222)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeTask(ClientInstaller.java:139)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.lambda$addTask$1(ClientInstaller.java:87)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: timeout
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:419)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:397)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:763)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:232)
        ... 20 common frames omitted
Caused by: java.io.InterruptedIOException: timeout
        at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
        at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
        at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        ... 3 common frames omitted
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        ... 4 common frames omitted

2024-07-03T14:47:57.055Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Error occurred while executing task #0
2024-07-03T14:47:57.055Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Task execution result #0: success=true
2024-07-03T14:47:57.055Z  WARN 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: NODE_REGISTRY_ENTRY status is still INSTALLING after executing client installation. Changing to INSTALL_ERROR
2024-07-03T14:47:57.059Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Client installation Task #0: result=SUCCESS, duration=130749ms
2024-07-03T14:47:57.061Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Sending SUCCESS execution report for Task #0: destination=ems.client.installation.reports, report={nodeInfo={}, deviceId=dummy-1720017946283, status=SUCCESS, timestamp=1720018077061, deviceIpAddress=unknown-address-1720017946306, requestType=INSTALL, requestId=, reference=e3e37e8f-1fb2-4d75-922b-ee9774866f4c}
```

EMS deamonsets:

```
2024-07-03T14:52:59.876Z ERROR 30 --- [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NumberFormatException: For input string: "null null"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
        at java.base/java.lang.Double.parseDouble(Unknown Source)
        at gr.iccs.imu.ems.baguette.client.collector.netdata.K8sNetdataCollector.collectDataFromNode(K8sNetdataCollector.java:413)
        at gr.iccs.imu.ems.baguette.client.collector.netdata.K8sNetdataCollector.collectData(K8sNetdataCollector.java:366)
        at gr.iccs.imu.ems.baguette.client.collector.netdata.K8sNetdataCollector.lambda$doStart$4(K8sNetdataCollector.java:321)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by robert-sanfeliu** [comment]
Shouldn't CPU use be expressed like this?
"netdata k8s.cgroup.cpu"

**Comment by ipatini** [comment]
This is the same as Issue #10

**Comment by ipatini** [comment]
So i'm closing it
