### ISSUE TITLE
EMS not starting properly

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/monitoring#32]
During the deployment of an application, EMS didn't create the deamons for the different PODs.
Environment: nebulous-cd
ems-server was installed:

![image](https://github.com/user-attachments/assets/76a31cdf-c9c9-4b06-9a09-96218e55d577)

And it showed the following error:

```
ubuntu@m15194-26-master-15194-26:~$ kubectl logs -f ems-ems-server-7976656d59-5rbc9
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
LANG=C.UTF-8
EMS_CONFIG_DIR=/opt/ems-server/config
EMS_CONFIG_LOCATION=optional:classpath:rule-templates.yml,optional:file:/opt/ems-server/config/ems-server.yml,optional:file:/opt/ems-server/config/ems-server.properties,optional:file:/opt/ems-server/config/ems.yml,optional:file:/opt/ems-server/config/ems.properties,optional:file:/opt/ems-server/config/secrets.properties
IP address=10.0.0.53
Starting EMS server...
EMS Pid: 30

Event Management System (ems), v.7.0.0-SNAPSHOT, Mozilla Public License, v2.0
Copyright (C) 2017-2025 Institute of Communication and Computer Systems (imu.iccs.gr)

2024-09-03T13:34:52.733Z  INFO 30 --- [           main] o.s.boot.SpringApplication               :

 ███████╗███╗   ███╗███████╗     ██████╗ ██████╗ ███╗   ██╗████████╗██████╗  ██████╗ ██╗
 ██╔════╝████╗ ████║██╔════╝    ██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔═══██╗██║
 █████╗  ██╔████╔██║███████╗    ██║     ██║   ██║██╔██╗ ██║   ██║   ██████╔╝██║   ██║██║
 ██╔══╝  ██║╚██╔╝██║╚════██║    ██║     ██║   ██║██║╚██╗██║   ██║   ██╔══██╗██║   ██║██║
 ███████╗██║ ╚═╝ ██║███████║    ╚██████╗╚██████╔╝██║ ╚████║   ██║   ██║  ██║╚██████╔╝███████╗
 ╚══════╝╚═╝     ╚═╝╚══════╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝

 :: EMS Control ::                        (7.0.0-SNAPSHOT)
 :: Spring Boot ::                        (v3.2.8)
 :: Java (TM)   ::                        (21.0.3)
 :: Build Num.  :: 11a424bd1c774d33146c5a0e9a6f24cf872b0771
 :: Build Date  :: 2024-08-19 14:02:13.318+0300
 :: SCM Branch  :: master,   at Repos.: https://gitlab.com/nebulous-project/ems-main.git
 :: Image Tag   :: ems-server:2024-aug
 :: Description :: *****  Preparing EMS for NebulOus  *****
                  ==========  EMS Nebulous Docker Image details  ==========
 :: Build Num.  :: a78f79ea3a8c2e275e6fef2639cdabb6862d9060
 :: Build Date  :: 2024-08-19 14:02:55.657+0300
 :: SCM Branch  :: master,   at Repos.: https://gitlab.com/nebulous-project/ems-nebulous.git
 :: Image Tag   :: ems-server:2024-aug-nebulous
 :: Description :: EMS Nebulous Docker Image is based on the EMS Core Docker Image


2024-09-03T13:34:52.914Z  INFO 30 --- [           main] g.i.imu.ems.util.NetUtilPostProcessor    : NetUtilPostProcessor:  NetUtilPropertySource registered (deferred log)
2024-09-03T13:34:52.937Z  INFO 30 --- [           main] g.i.i.e.c.ControlServiceApplication      : Starting ControlServiceApplication using Java 21.0.3 with PID 30 (/opt/ems-server/BOOT-INF/classes started by emsuser in /opt/ems-server)
2024-09-03T13:34:52.939Z  INFO 30 --- [           main] g.i.i.e.c.ControlServiceApplication      : No active profile set, falling back to 1 default profile: "default"
2024-09-03T13:34:56.980Z  INFO 30 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2024-09-03T13:34:56.994Z  INFO 30 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2024-09-03T13:34:58.344Z  WARN 30 --- [           main] gr.iccs.imu.ems.util.NetUtil             : NetUtil.getPublicIpAddress(): No Public IP address or connectivity problems exist
2024-09-03T13:34:58.617Z  INFO 30 --- [           main] gr.iccs.imu.ems.util.PasswordUtil        : PasswordUtil: Initialized default Password Encoder: gr.iccs.imu.ems.util.password.AsterisksPasswordEncoder
2024-09-03T13:35:01.019Z  INFO 30 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8111 (https)
2024-09-03T13:35:01.086Z  INFO 30 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-09-03T13:35:01.087Z  INFO 30 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-09-03T13:35:01.170Z  INFO 30 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-09-03T13:35:01.171Z  INFO 30 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7416 ms
2024-09-03T13:35:01.974Z  INFO 30 --- [           main] g.i.i.e.b.c.s.SelfHealingManagerImpl     : Self-Healing Manager initialized
2024-09-03T13:35:01.976Z  INFO 30 --- [           main] g.i.i.e.b.c.s.SelfHealingManagerImpl     : Recovery context: RecoveryContext(variablesMap={BAGUETTE_CLIENT_BASE_DIR=~/baguette-client})
2024-09-03T13:35:02.182Z  INFO 30 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer: Generated new username/password: username=user-d140b24d-ec32-44d6-a833-6ee8dbb0c1fa, password=********
2024-09-03T13:35:02.875Z  INFO 30 --- [           main] eu.nebulous.ems.EmsNebulousProperties    : EmsNebulousProperties(applicationId=1519490309rest-processor-app1725369589509, appId=null, appUid=null, appUuid=null, emsServerPodUid=fe870809-1b04-4812-8359-b9fba99905d3, emsServerPodNamespace=default, appPodLabel=app)
2024-09-03T13:35:02.882Z  INFO 30 --- [           main] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Application Id (from Env.): 1519490309rest-processor-app1725369589509
2024-09-03T13:35:03.653Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Loaded the Bouncy Castle security provider at position: -1
2024-09-03T13:35:04.139Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Using Persistence Adapter: MemoryPersistenceAdapter
2024-09-03T13:35:04.140Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Persistence Adapter: MemoryPersistenceAdapter
2024-09-03T13:35:04.140Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Temp Data Store
2024-09-03T13:35:04.140Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Job Scheduler Store
2024-09-03T13:35:04.140Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Persistence Adapter successfully started
2024-09-03T13:35:04.283Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 6.1.2 (broker, ID:ems-ems-server-7976656d59-5rbc9-42251-1725370504153-0:1) is starting
2024-09-03T13:35:04.294Z  INFO 30 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: ssl://ems-ems-server-7976656d59-5rbc9:61617?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true
2024-09-03T13:35:04.294Z  INFO 30 --- [           main] o.a.activemq.broker.TransportConnector   : Connector ssl://ems-ems-server-7976656d59-5rbc9:61617?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true started
2024-09-03T13:35:04.295Z  INFO 30 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: tcp://ems-ems-server-7976656d59-5rbc9:61616?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true
2024-09-03T13:35:04.296Z  INFO 30 --- [           main] o.a.activemq.broker.TransportConnector   : Connector tcp://ems-ems-server-7976656d59-5rbc9:61616?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true started
2024-09-03T13:35:04.297Z  INFO 30 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: stomp://ems-ems-server-7976656d59-5rbc9:61610
2024-09-03T13:35:04.297Z  INFO 30 --- [           main] o.a.activemq.broker.TransportConnector   : Connector stomp://ems-ems-server-7976656d59-5rbc9:61610 started
2024-09-03T13:35:04.298Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 6.1.2 (broker, ID:ems-ems-server-7976656d59-5rbc9-42251-1725370504153-0:1) started
2024-09-03T13:35:04.298Z  INFO 30 --- [           main] o.apache.activemq.broker.BrokerService   : For help or more information please see: http://activemq.apache.org
2024-09-03T13:35:04.317Z  INFO 30 --- [       Thread-5] .i.i.e.b.b.i.MessageForwarderInterceptor : MessageQueueProcessor: Starts processing message queue and forward messages
2024-09-03T13:35:04.389Z  INFO 30 --- [           main] c.e.e.c.service.EPServiceProviderImpl    : Initializing engine URI 'default' version 7.1.0
2024-09-03T13:35:04.886Z  INFO 30 --- [           main] e.n.ems.translate.NebulousEmsTranslator  : NebulousEmsTranslator: initialized
2024-09-03T13:35:04.969Z  INFO 30 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.initTranslator(): Effective translator: eu.nebulous.ems.translate.NebulousEmsTranslator
2024-09-03T13:35:04.971Z  INFO 30 --- [           main] eu.nebulous.ems.service.MvvService       : MvvService: initialized
2024-09-03T13:35:04.972Z  INFO 30 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server...
2024-09-03T13:35:04.976Z  INFO 30 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : ** SSH server **
2024-09-03T13:35:04.977Z  INFO 30 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Public IP address: 10.0.0.53
2024-09-03T13:35:04.978Z  INFO 30 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:  Starting on port: 2222
2024-09-03T13:35:04.979Z  INFO 30 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:   Server key file: /opt/ems-server/config/hostkey.pem
2024-09-03T13:35:05.157Z  INFO 30 --- [           main] s.c.u.s.e.EdDSASecurityProviderRegistrar : getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
2024-09-03T13:35:05.412Z  INFO 30 --- [           main] o.a.s.s.k.SimpleGeneratorHostKeyProvider : generateKeyPair(EC) generating host key=nistp521
2024-09-03T13:35:05.677Z  INFO 30 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Ready
2024-09-03T13:35:05.685Z  INFO 30 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server... done
2024-09-03T13:35:05.688Z  INFO 30 --- [       Thread-6] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Started: period=60000ms
2024-09-03T13:35:05.820Z  INFO 30 --- [           main] g.iccs.imu.ems.control.util.TopicBeacon  : Topic Beacon started: init-delay=60000ms, delay=60000ms
2024-09-03T13:35:05.833Z  INFO 30 --- [           main] g.i.imu.ems.common.plugin.PluginManager  : PluginManager: Started
2024-09-03T13:35:06.140Z  INFO 30 --- [           main] g.iccs.imu.ems.brokercep.EventForwarder  : EventForwarder: Starting event publish/forward worker
2024-09-03T13:35:06.191Z  INFO 30 --- [           main] gr.iccs.imu.ems.brokercep.StatsPrinter   : BCEP Statistics Printer disabled
2024-09-03T13:35:06.454Z  INFO 30 --- [           main] g.i.i.e.c.misc.SystemResourceMonitor     : SystemResourceMonitor started
2024-09-03T13:35:06.784Z  INFO 30 --- [           main] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerPrometheusCollector: New Allowed Topics: null -- Topics Map: null
2024-09-03T13:35:07.086Z  INFO 30 --- [           main] .c.i.ControlServiceInfoEndpointExtension : Info endpoint is enabled and exposed. Added EMS info extension.
2024-09-03T13:35:07.138Z  INFO 30 --- [           main] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerNetdataCollector: New Allowed Topics: null -- Topics Map: null
2024-09-03T13:35:07.284Z  INFO 30 --- [           main] eu.nebulous.ems.k8s.K8sPodWatcher        : K8sPodWatcher: Enabled  (running every PT1M, init-delay=PT30S)
2024-09-03T13:35:07.295Z  INFO 30 --- [           main] eu.nebulous.ems.boot.EmsBootProperties   : EmsBootProperties(enabled=false, processorPeriod=500, applicationIdPropertyName=application, modelsDir=models, modelsIndexFile=models/index.json, dslTopic=eu.nebulouscloud.ui.dsl.generic, optimiserMetricsTopic=eu.nebulouscloud.optimiser.controller.metric_list, modelsTopic=eu.nebulouscloud.ui.dsl.metric_model, modelsResponseTopic=eu.nebulouscloud.ui.dsl.metric_model.reply, emsBootTopic=eu.nebulouscloud.ems.boot, emsBootResponseTopic=eu.nebulouscloud.ems.boot.reply, validateModels=true, storeInvalidModels=true, reportInvalidModels=true)
2024-09-03T13:35:07.334Z  INFO 30 --- [           main] eu.nebulous.ems.boot.ModelsService       : ModelsService is disabled because EMS Boot is disabled
2024-09-03T13:35:07.340Z  INFO 30 --- [           main] e.n.ems.boot.NebulousEventsService       : EMS Boot is disabled
2024-09-03T13:35:07.354Z  INFO 30 --- [           main] e.n.e.s.EmsBootInitializerProperties     : EmsBootInitializerProperties(enabled=true, initialWait=PT1S, retryPeriod=PT30S)
2024-09-03T13:35:07.378Z  INFO 30 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: Application Id: 1519490309rest-processor-app1725369589509
2024-09-03T13:35:08.000Z  INFO 30 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: created subscribers
2024-09-03T13:35:08.004Z  INFO 30 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: created publishers
2024-09-03T13:35:08.203Z  INFO 30 --- [           main] eu.nebulouscloud.exn.Connector           : Starting connector...
2024-09-03T13:35:08.420Z  INFO 30 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 2 consumers
2024-09-03T13:35:09.118Z  INFO 30 --- [:1): I/O Thread] o.a.q.p.client.impl.ClientConnection     : Connection ID:5735198d-5347-40be-be87-c7854b7aed76:1:1 connected to server: 158.37.63.86:32754
2024-09-03T13:35:09.366Z  INFO 30 --- [pool-6-thread-2] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.monitoring.commands
2024-09-03T13:35:09.592Z  INFO 30 --- [pool-6-thread-3] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.optimiser.solver.solution
2024-09-03T13:35:09.593Z  INFO 30 --- [pool-6-thread-3] eu.nebulouscloud.exn.core.Manager        :       for application 1519490309rest-processor-app1725369589509
2024-09-03T13:35:09.593Z  INFO 30 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 1 publishers
2024-09-03T13:35:09.604Z  INFO 30 --- [           main] e.n.e.s.AbstractExternalBrokerService    : AbstractExternalBrokerService: Connected to broker
2024-09-03T13:35:09.604Z  INFO 30 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: Initialized listeners and publishers
2024-09-03T13:35:09.613Z  INFO 30 --- [           main] e.n.ems.translate.analyze.AnalysisUtils  : AnalysisUtils: useCompositeNames: false
2024-09-03T13:35:10.630Z  INFO 30 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2024-09-03T13:35:10.714Z  INFO 30 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@51049621, org.springframework.security.web.session.ForceEagerSessionCreationFilter@2c17ebb7, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@2b867623, org.springframework.security.web.context.SecurityContextHolderFilter@57fd93f9, org.springframework.security.web.header.HeaderWriterFilter@234ad505, org.springframework.web.filter.CorsFilter@6c8590f4, org.springframework.security.web.authentication.logout.LogoutFilter@78c0fad6, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@447dec7e, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x000073840cb894d0@1945b6db, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x000073840cb89710@a1cac17, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x000073840cb89950@1233f419, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x000073840cb89b90@5271c49b, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1a7f6678, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@9e2946, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@66b65360, org.springframework.security.web.session.SessionManagementFilter@4655e059, org.springframework.security.web.access.ExceptionTranslationFilter@716205f9, org.springframework.security.web.access.intercept.AuthorizationFilter@11e2de88]
2024-09-03T13:35:10.895Z  WARN 30 --- [           main] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Thymeleaf configuration, or set spring.thymeleaf.check-template-location=false)
2024-09-03T13:35:11.436Z  WARN 30 --- [           main] .b.a.g.t.GroovyTemplateAutoConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Groovy configuration, or set spring.groovy.template.check-template-location=false)
2024-09-03T13:35:12.300Z  INFO 30 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2024-09-03T13:35:12.301Z  INFO 30 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application.errorChannel' has 1 subscriber(s).
2024-09-03T13:35:12.315Z  INFO 30 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2024-09-03T13:35:12.548Z  INFO 30 --- [           main] o.a.t.util.net.NioEndpoint.certificate   : Connector [https-jsse-nio-8111], TLS virtual host [_default_], certificate type [UNDEFINED] configured from keystore [/opt/ems-server/.keystore] using alias [ems] with trust store [null]
2024-09-03T13:35:12.561Z  INFO 30 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8111 (https) with context path ''
2024-09-03T13:35:12.565Z  INFO 30 --- [           main] i.i.e.b.c.i.h.AbstractInstallationHelper : Server PEM certificate stored in file: /opt/ems-server/config/server.pem
2024-09-03T13:35:12.566Z  INFO 30 --- [           main] i.i.e.b.c.i.h.AbstractInstallationHelper : Server PEM certificate stored in file: /opt/ems-server/config/server.pem
2024-09-03T13:35:12.637Z  INFO 30 --- [           main] g.i.i.e.c.ControlServiceApplication      : Started ControlServiceApplication in 20.824 seconds (process running for 21.91)
2024-09-03T13:35:12.702Z  INFO 30 --- [           main] e.n.ems.service.EmsBootInitializer       : ===================> EMS is ready -- Scheduling EMS Boot message -- App Id: 1519490309rest-processor-app1725369589509
2024-09-03T13:35:12.719Z  INFO 30 --- [           main] eu.nebulouscloud.exn.Connector           : Starting connector...
2024-09-03T13:35:12.725Z  INFO 30 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 1 consumers
2024-09-03T13:35:13.255Z  INFO 30 --- [:1): I/O Thread] o.a.q.p.client.impl.ClientConnection     : Connection ID:0830951a-b22e-44b7-95c0-f0b3a5c0d635:2:1 connected to server: 158.37.63.86:32754
2024-09-03T13:35:13.504Z  INFO 30 --- [pool-8-thread-2] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.ems.boot.reply
2024-09-03T13:35:13.505Z  INFO 30 --- [pool-8-thread-2] eu.nebulouscloud.exn.core.Manager        :       for application 1519490309rest-processor-app1725369589509
2024-09-03T13:35:13.505Z  INFO 30 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 2 publishers
2024-09-03T13:35:13.509Z  INFO 30 --- [           main] e.n.e.s.AbstractExternalBrokerService    : AbstractExternalBrokerService: Connected to broker
2024-09-03T13:35:13.511Z  INFO 30 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.applicationReady(): IP setting: DEFAULT_IP
2024-09-03T13:35:13.511Z  INFO 30 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.preloadModels(): No model to preload
2024-09-03T13:35:13.512Z  INFO 30 --- [           main] g.i.i.e.c.ControlServiceApplication      : EMS server initialized in 21876ms
2024-09-03T13:53:38.290Z  WARN 30 --- [ scheduling-133] i.f.kubernetes.client.internal.SSLUtils  : SSL handshake failed. Falling back to insecure connection.
2024-09-03T13:55:47.439Z  WARN 30 --- [ scheduling-133] gr.iccs.imu.ems.common.k8s.K8sClient     : K8sClient.getRunningPodsInfo: EXCEPTION while retrieving pods:

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [null]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:453)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:419)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.resources(BaseOperation.java:1115)
        at gr.iccs.imu.ems.common.k8s.K8sClient.getRunningPodsInfo(K8sClient.java:280)
        at eu.nebulous.ems.k8s.K8sPodWatcher.doWatch(K8sPodWatcher.java:66)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.lang.VirtualThread.run(Unknown Source)
Caused by: java.io.IOException: timeout
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:451)
        ... 6 common frames omitted
Caused by: java.io.InterruptedIOException: timeout
        at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
        at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
        at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        ... 4 common frames omitted

```

**Comment by ipatini** [comment]
This log indicates a fail attempt to contact K8s API server to get a list of pods. This should not be a problem if a subsequent call succeeds (unfortunately the next log lines are not included). The exact reason seems to be a socket timeout while waiting for API server response.
