### ISSUE TITLE
EMS fails to create deamonsets

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/monitoring#34]
```
ubuntu@m13345-12-master-13345-12:~$ kubectl logs ems-ems-server-665446799-lcr56
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
LANG=C.UTF-8
EMS_CONFIG_DIR=/opt/ems-server/config
EMS_CONFIG_LOCATION=optional:classpath:rule-templates.yml,optional:file:/opt/ems-server/config/ems-server.yml,optional:file:/opt/ems-server/config/ems-server.properties,optional:file:/opt/ems-server/config/ems.yml,optional:file:/opt/ems-server/config/ems.properties,optional:file:/opt/ems-server/config/secrets.properties
IP address=10.0.0.188
Starting EMS server...
EMS Pid: 29

Event Management System (ems), v.7.0.0-SNAPSHOT, Mozilla Public License, v2.0
Copyright (C) 2017-2025 Institute of Communication and Computer Systems (imu.iccs.gr)

2024-09-27T11:49:27.109Z  INFO 29 --- [           main] o.s.boot.SpringApplication               :

 ███████╗███╗   ███╗███████╗     ██████╗ ██████╗ ███╗   ██╗████████╗██████╗  ██████╗ ██╗
 ██╔════╝████╗ ████║██╔════╝    ██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔═══██╗██║
 █████╗  ██╔████╔██║███████╗    ██║     ██║   ██║██╔██╗ ██║   ██║   ██████╔╝██║   ██║██║
 ██╔══╝  ██║╚██╔╝██║╚════██║    ██║     ██║   ██║██║╚██╗██║   ██║   ██╔══██╗██║   ██║██║
 ███████╗██║ ╚═╝ ██║███████║    ╚██████╗╚██████╔╝██║ ╚████║   ██║   ██║  ██║╚██████╔╝███████╗
 ╚══════╝╚═╝     ╚═╝╚══════╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝

 :: EMS Control ::                        (7.0.0-SNAPSHOT)
 :: Spring Boot ::                        (v3.2.8)
 :: Java (TM)   ::                        (21.0.3)
 :: Build Num.  :: 11a424bd1c774d33146c5a0e9a6f24cf872b0771
 :: Build Date  :: 2024-08-19 14:02:13.318+0300
 :: SCM Branch  :: master,   at Repos.: https://gitlab.com/nebulous-project/ems-main.git
 :: Image Tag   :: ems-server:2024-aug
 :: Description :: *****  Preparing EMS for NebulOus  *****
                  ==========  EMS Nebulous Docker Image details  ==========
 :: Build Num.  :: a78f79ea3a8c2e275e6fef2639cdabb6862d9060
 :: Build Date  :: 2024-08-19 14:02:55.657+0300
 :: SCM Branch  :: master,   at Repos.: https://gitlab.com/nebulous-project/ems-nebulous.git
 :: Image Tag   :: ems-server:2024-aug-nebulous
 :: Description :: EMS Nebulous Docker Image is based on the EMS Core Docker Image


2024-09-27T11:49:27.321Z  INFO 29 --- [           main] g.i.imu.ems.util.NetUtilPostProcessor    : NetUtilPostProcessor:  NetUtilPropertySource registered (deferred log)
2024-09-27T11:49:27.339Z  INFO 29 --- [           main] g.i.i.e.c.ControlServiceApplication      : Starting ControlServiceApplication using Java 21.0.3 with PID 29 (/opt/ems-server/BOOT-INF/classes started by emsuser in /opt/ems-server)
2024-09-27T11:49:27.342Z  INFO 29 --- [           main] g.i.i.e.c.ControlServiceApplication      : No active profile set, falling back to 1 default profile: "default"
2024-09-27T11:49:31.057Z  INFO 29 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2024-09-27T11:49:31.072Z  INFO 29 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2024-09-27T11:49:32.148Z  WARN 29 --- [           main] gr.iccs.imu.ems.util.NetUtil             : NetUtil.getPublicIpAddress(): No Public IP address or connectivity problems exist
2024-09-27T11:49:32.401Z  INFO 29 --- [           main] gr.iccs.imu.ems.util.PasswordUtil        : PasswordUtil: Initialized default Password Encoder: gr.iccs.imu.ems.util.password.AsterisksPasswordEncoder
2024-09-27T11:49:34.834Z  INFO 29 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8111 (https)
2024-09-27T11:49:34.867Z  INFO 29 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-09-27T11:49:34.868Z  INFO 29 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-09-27T11:49:34.975Z  INFO 29 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-09-27T11:49:34.977Z  INFO 29 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6947 ms
2024-09-27T11:49:35.726Z  INFO 29 --- [           main] g.i.i.e.b.c.s.SelfHealingManagerImpl     : Self-Healing Manager initialized
2024-09-27T11:49:35.727Z  INFO 29 --- [           main] g.i.i.e.b.c.s.SelfHealingManagerImpl     : Recovery context: RecoveryContext(variablesMap={BAGUETTE_CLIENT_BASE_DIR=~/baguette-client})
2024-09-27T11:49:35.943Z  INFO 29 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer: Generated new username/password: username=user-34df5f6e-01f3-45ed-8b4f-b029cb4eae30, password=********
2024-09-27T11:49:36.616Z  INFO 29 --- [           main] eu.nebulous.ems.EmsNebulousProperties    : EmsNebulousProperties(applicationId=1334532709rest-processor-app1727436893788, appId=null, appUid=null, appUuid=null, emsServerPodUid=526412e2-c9b9-4860-9e9c-a0e0adbb2666, emsServerPodNamespace=default, appPodLabel=app)
2024-09-27T11:49:36.621Z  INFO 29 --- [           main] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Application Id (from Env.): 1334532709rest-processor-app1727436893788
2024-09-27T11:49:37.223Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Loaded the Bouncy Castle security provider at position: -1
2024-09-27T11:49:37.596Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Using Persistence Adapter: MemoryPersistenceAdapter
2024-09-27T11:49:37.601Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Persistence Adapter: MemoryPersistenceAdapter
2024-09-27T11:49:37.601Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Temp Data Store
2024-09-27T11:49:37.602Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Starting Job Scheduler Store
2024-09-27T11:49:37.602Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Persistence Adapter successfully started
2024-09-27T11:49:37.770Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 6.1.2 (broker, ID:ems-ems-server-665446799-lcr56-43941-1727437777617-0:1) is starting
2024-09-27T11:49:37.779Z  INFO 29 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: ssl://ems-ems-server-665446799-lcr56:61617?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true
2024-09-27T11:49:37.779Z  INFO 29 --- [           main] o.a.activemq.broker.TransportConnector   : Connector ssl://ems-ems-server-665446799-lcr56:61617?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true started
2024-09-27T11:49:37.781Z  INFO 29 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: tcp://ems-ems-server-665446799-lcr56:61616?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true
2024-09-27T11:49:37.781Z  INFO 29 --- [           main] o.a.activemq.broker.TransportConnector   : Connector tcp://ems-ems-server-665446799-lcr56:61616?transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=false&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true started
2024-09-27T11:49:37.783Z  INFO 29 --- [           main] o.a.a.t.TransportServerThreadSupport     : Listening for connections at: stomp://ems-ems-server-665446799-lcr56:61610
2024-09-27T11:49:37.785Z  INFO 29 --- [           main] o.a.activemq.broker.TransportConnector   : Connector stomp://ems-ems-server-665446799-lcr56:61610 started
2024-09-27T11:49:37.785Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 6.1.2 (broker, ID:ems-ems-server-665446799-lcr56-43941-1727437777617-0:1) started
2024-09-27T11:49:37.786Z  INFO 29 --- [           main] o.apache.activemq.broker.BrokerService   : For help or more information please see: http://activemq.apache.org
2024-09-27T11:49:37.820Z  INFO 29 --- [       Thread-5] .i.i.e.b.b.i.MessageForwarderInterceptor : MessageQueueProcessor: Starts processing message queue and forward messages
2024-09-27T11:49:37.946Z  INFO 29 --- [           main] c.e.e.c.service.EPServiceProviderImpl    : Initializing engine URI 'default' version 7.1.0
2024-09-27T11:49:38.608Z  INFO 29 --- [           main] e.n.ems.translate.NebulousEmsTranslator  : NebulousEmsTranslator: initialized
2024-09-27T11:49:38.746Z  INFO 29 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.initTranslator(): Effective translator: eu.nebulous.ems.translate.NebulousEmsTranslator
2024-09-27T11:49:38.747Z  INFO 29 --- [           main] eu.nebulous.ems.service.MvvService       : MvvService: initialized
2024-09-27T11:49:38.748Z  INFO 29 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server...
2024-09-27T11:49:38.751Z  INFO 29 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : ** SSH server **
2024-09-27T11:49:38.754Z  INFO 29 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Public IP address: 10.0.0.188
2024-09-27T11:49:38.754Z  INFO 29 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:  Starting on port: 2222
2024-09-27T11:49:38.755Z  INFO 29 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:   Server key file: /opt/ems-server/config/hostkey.pem
2024-09-27T11:49:38.841Z  INFO 29 --- [           main] s.c.u.s.e.EdDSASecurityProviderRegistrar : getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
2024-09-27T11:49:39.072Z  INFO 29 --- [           main] o.a.s.s.k.SimpleGeneratorHostKeyProvider : generateKeyPair(EC) generating host key=nistp521
2024-09-27T11:49:39.266Z  INFO 29 --- [           main] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Ready
2024-09-27T11:49:39.268Z  INFO 29 --- [           main] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server... done
2024-09-27T11:49:39.268Z  INFO 29 --- [       Thread-6] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Started: period=60000ms
2024-09-27T11:49:39.370Z  INFO 29 --- [           main] g.iccs.imu.ems.control.util.TopicBeacon  : Topic Beacon started: init-delay=60000ms, delay=60000ms
2024-09-27T11:49:39.407Z  INFO 29 --- [           main] g.i.imu.ems.common.plugin.PluginManager  : PluginManager: Started
2024-09-27T11:49:39.647Z  INFO 29 --- [           main] g.iccs.imu.ems.brokercep.EventForwarder  : EventForwarder: Starting event publish/forward worker
2024-09-27T11:49:39.679Z  INFO 29 --- [           main] gr.iccs.imu.ems.brokercep.StatsPrinter   : BCEP Statistics Printer disabled
2024-09-27T11:49:39.845Z  INFO 29 --- [           main] g.i.i.e.c.misc.SystemResourceMonitor     : SystemResourceMonitor started
2024-09-27T11:49:40.167Z  INFO 29 --- [           main] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerPrometheusCollector: New Allowed Topics: null -- Topics Map: null
2024-09-27T11:49:40.396Z  INFO 29 --- [           main] .c.i.ControlServiceInfoEndpointExtension : Info endpoint is enabled and exposed. Added EMS info extension.
2024-09-27T11:49:40.410Z  INFO 29 --- [           main] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerNetdataCollector: New Allowed Topics: null -- Topics Map: null
2024-09-27T11:49:40.474Z  INFO 29 --- [           main] eu.nebulous.ems.k8s.K8sPodWatcher        : K8sPodWatcher: Enabled  (running every PT1M, init-delay=PT30S)
2024-09-27T11:49:40.482Z  INFO 29 --- [           main] eu.nebulous.ems.boot.EmsBootProperties   : EmsBootProperties(enabled=false, processorPeriod=500, applicationIdPropertyName=application, modelsDir=models, modelsIndexFile=models/index.json, dslTopic=eu.nebulouscloud.ui.dsl.generic, optimiserMetricsTopic=eu.nebulouscloud.optimiser.controller.metric_list, modelsTopic=eu.nebulouscloud.ui.dsl.metric_model, modelsResponseTopic=eu.nebulouscloud.ui.dsl.metric_model.reply, emsBootTopic=eu.nebulouscloud.ems.boot, emsBootResponseTopic=eu.nebulouscloud.ems.boot.reply, validateModels=true, storeInvalidModels=true, reportInvalidModels=true)
2024-09-27T11:49:40.501Z  INFO 29 --- [           main] eu.nebulous.ems.boot.ModelsService       : ModelsService is disabled because EMS Boot is disabled
2024-09-27T11:49:40.503Z  INFO 29 --- [           main] e.n.ems.boot.NebulousEventsService       : EMS Boot is disabled
2024-09-27T11:49:40.507Z  INFO 29 --- [           main] e.n.e.s.EmsBootInitializerProperties     : EmsBootInitializerProperties(enabled=true, initialWait=PT1S, retryPeriod=PT30S)
2024-09-27T11:49:40.515Z  INFO 29 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: Application Id: 1334532709rest-processor-app1727436893788
2024-09-27T11:49:41.060Z  INFO 29 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: created subscribers
2024-09-27T11:49:41.068Z  INFO 29 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: created publishers
2024-09-27T11:49:41.280Z  INFO 29 --- [           main] eu.nebulouscloud.exn.Connector           : Starting connector...
2024-09-27T11:49:41.504Z  INFO 29 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 2 consumers
2024-09-27T11:49:42.360Z  INFO 29 --- [:1): I/O Thread] o.a.q.p.client.impl.ClientConnection     : Connection ID:5be429c9-2095-4001-a06d-0d7744262b9c:1:1 connected to server: 158.37.63.86:32754
2024-09-27T11:49:42.610Z  INFO 29 --- [pool-6-thread-2] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.monitoring.commands
2024-09-27T11:49:42.846Z  INFO 29 --- [pool-6-thread-3] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.optimiser.solver.solution
2024-09-27T11:49:42.847Z  INFO 29 --- [pool-6-thread-3] eu.nebulouscloud.exn.core.Manager        :       for application 1334532709rest-processor-app1727436893788
2024-09-27T11:49:42.847Z  INFO 29 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 1 publishers
2024-09-27T11:49:42.859Z  INFO 29 --- [           main] e.n.e.s.AbstractExternalBrokerService    : AbstractExternalBrokerService: Connected to broker
2024-09-27T11:49:42.859Z  INFO 29 --- [           main] e.n.e.s.ExternalBrokerListenerService    : ExternalBrokerListenerService: Initialized listeners and publishers
2024-09-27T11:49:42.865Z  INFO 29 --- [           main] e.n.ems.translate.analyze.AnalysisUtils  : AnalysisUtils: useCompositeNames: false
2024-09-27T11:49:43.965Z  INFO 29 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2024-09-27T11:49:44.147Z  INFO 29 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@46135aba, org.springframework.security.web.session.ForceEagerSessionCreationFilter@25a218a, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@411e5672, org.springframework.security.web.context.SecurityContextHolderFilter@6fc1d215, org.springframework.security.web.header.HeaderWriterFilter@37c5e2e6, org.springframework.web.filter.CorsFilter@1efdaec0, org.springframework.security.web.authentication.logout.LogoutFilter@7c057419, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@7b51fc45, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x00007a08e0b9b5e0@42e7e12f, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x00007a08e0b9b820@11e2de88, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x00007a08e0b9ba60@227ca700, gr.iccs.imu.ems.control.webconf.WebSecurityConfig$$Lambda/0x00007a08e0b9bca0@51049621, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@27796482, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@2765c3fc, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@2c17ebb7, org.springframework.security.web.session.SessionManagementFilter@5c9844a4, org.springframework.security.web.access.ExceptionTranslationFilter@711329fe, org.springframework.security.web.access.intercept.AuthorizationFilter@4cc1f8d3]
2024-09-27T11:49:44.437Z  WARN 29 --- [           main] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Thymeleaf configuration, or set spring.thymeleaf.check-template-location=false)
2024-09-27T11:49:44.931Z  WARN 29 --- [           main] .b.a.g.t.GroovyTemplateAutoConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Groovy configuration, or set spring.groovy.template.check-template-location=false)
2024-09-27T11:49:45.628Z  INFO 29 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2024-09-27T11:49:45.629Z  INFO 29 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application.errorChannel' has 1 subscriber(s).
2024-09-27T11:49:45.630Z  INFO 29 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2024-09-27T11:49:45.777Z  INFO 29 --- [           main] o.a.t.util.net.NioEndpoint.certificate   : Connector [https-jsse-nio-8111], TLS virtual host [_default_], certificate type [UNDEFINED] configured from keystore [/opt/ems-server/.keystore] using alias [ems] with trust store [null]
2024-09-27T11:49:45.784Z  INFO 29 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8111 (https) with context path ''
2024-09-27T11:49:45.788Z  INFO 29 --- [           main] i.i.e.b.c.i.h.AbstractInstallationHelper : Server PEM certificate stored in file: /opt/ems-server/config/server.pem
2024-09-27T11:49:45.789Z  INFO 29 --- [           main] i.i.e.b.c.i.h.AbstractInstallationHelper : Server PEM certificate stored in file: /opt/ems-server/config/server.pem
2024-09-27T11:49:45.829Z  INFO 29 --- [           main] g.i.i.e.c.ControlServiceApplication      : Started ControlServiceApplication in 19.552 seconds (process running for 20.653)
2024-09-27T11:49:45.841Z  INFO 29 --- [           main] e.n.ems.service.EmsBootInitializer       : ===================> EMS is ready -- Scheduling EMS Boot message -- App Id: 1334532709rest-processor-app1727436893788
2024-09-27T11:49:45.847Z  INFO 29 --- [           main] eu.nebulouscloud.exn.Connector           : Starting connector...
2024-09-27T11:49:45.848Z  INFO 29 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 1 consumers
2024-09-27T11:49:46.374Z  INFO 29 --- [:1): I/O Thread] o.a.q.p.client.impl.ClientConnection     : Connection ID:1329d6e4-129b-477c-b1e4-8de19244d7f2:2:1 connected to server: 158.37.63.86:32754
2024-09-27T11:49:46.626Z  INFO 29 --- [pool-8-thread-2] eu.nebulouscloud.exn.core.Manager        : Linking consumer topic://eu.nebulouscloud.ems.boot.reply
2024-09-27T11:49:46.626Z  INFO 29 --- [pool-8-thread-2] eu.nebulouscloud.exn.core.Manager        :       for application 1334532709rest-processor-app1727436893788
2024-09-27T11:49:46.626Z  INFO 29 --- [           main] eu.nebulouscloud.exn.core.Context        : Registering 2 publishers
2024-09-27T11:49:46.630Z  INFO 29 --- [           main] e.n.e.s.AbstractExternalBrokerService    : AbstractExternalBrokerService: Connected to broker
2024-09-27T11:49:46.631Z  INFO 29 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.applicationReady(): IP setting: DEFAULT_IP
2024-09-27T11:49:46.632Z  INFO 29 --- [           main] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.preloadModels(): No model to preload
2024-09-27T11:49:46.633Z  INFO 29 --- [           main] g.i.i.e.c.ControlServiceApplication      : EMS server initialized in 20516ms
2024-09-27T12:04:11.479Z  WARN 29 --- [ scheduling-105] i.f.kubernetes.client.internal.SSLUtils  : SSL handshake failed. Falling back to insecure connection.
2024-09-27T12:06:20.604Z  WARN 29 --- [ scheduling-105] gr.iccs.imu.ems.common.k8s.K8sClient     : K8sClient.getRunningPodsInfo: EXCEPTION while retrieving pods:

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [null]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:453)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:419)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.resources(BaseOperation.java:1115)
        at gr.iccs.imu.ems.common.k8s.K8sClient.getRunningPodsInfo(K8sClient.java:280)
        at eu.nebulous.ems.k8s.K8sPodWatcher.doWatch(K8sPodWatcher.java:66)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.lang.VirtualThread.run(Unknown Source)
Caused by: java.io.IOException: timeout
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:451)
        ... 6 common frames omitted
Caused by: java.io.InterruptedIOException: timeout
        at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
        at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
        at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        ... 4 common frames omitted

2024-09-27T12:06:20.607Z  WARN 29 --- [ scheduling-105] eu.nebulous.ems.k8s.K8sPodWatcher        : K8sPodWatcher: ERROR while running doWatch:

java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "gr.iccs.imu.ems.common.k8s.K8sClient.getRunningPodsInfo()" is null
        at eu.nebulous.ems.k8s.K8sPodWatcher.doWatch(K8sPodWatcher.java:66)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.lang.VirtualThread.run(Unknown Source)

```

**Comment by ipatini** [comment]
I close this issue since the attached log is not related to the real problem that relates to exn moddleware
