### ISSUE TITLE
Crash when SLO is empty

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/monitoring#42]
When the SLO for an application is empty. EMS on control plane crashes with:

```
2024-12-09T14:48:48.870Z ERROR 30 --- [heduling-709492] e.n.ems.translate.analyze.AnalysisUtils  : AnalysisUtils.asMap: input:
2024-12-09T14:48:48.870Z ERROR 30 --- [heduling-709492] e.n.ems.translate.analyze.AnalysisUtils  : Parse error: Object is not a Map:
2024-12-09T14:48:48.871Z ERROR 30 --- [heduling-709492] e.n.ems.translate.NebulousEmsTranslator  : NebulousEmsTranslator: EXCEPTION while translating metric model file: eu.nebulous.ems.translate.ModelException: Object is not a Map:
Exception:

java.lang.RuntimeException: eu.nebulous.ems.translate.ModelException: Object is not a Map:
        at eu.nebulous.ems.translate.analyze.AnalysisUtils.createException(AnalysisUtils.java:52)
        at eu.nebulous.ems.translate.analyze.AnalysisUtils.asMap(AnalysisUtils.java:71)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.lambda$buildElementLists$12(MetricModelAnalyzer.java:311)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.lambda$buildElementLists$14(MetricModelAnalyzer.java:305)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.buildElementLists(MetricModelAnalyzer.java:287)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.analyzeModel(MetricModelAnalyzer.java:113)
        at eu.nebulous.ems.translate.NebulousEmsTranslator.translate(NebulousEmsTranslator.java:207)
        at eu.nebulous.ems.translate.NebulousEmsTranslator.translate(NebulousEmsTranslator.java:102)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.translateAppModelAndStore(ControlServiceCoordinator.java:566)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator._translateAppModel(ControlServiceCoordinator.java:344)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.lambda$translateAppModel$2(ControlServiceCoordinator.java:233)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator._lockAndProcessModel(ControlServiceCoordinator.java:290)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.translateAppModel(ControlServiceCoordinator.java:231)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator$$SpringCGLIB$$0.translateAppModel(<generated>)
        at eu.nebulous.ems.translate.TranslationService.translateModel(TranslationService.java:52)
        at eu.nebulous.ems.boot.ModelsService.processMetricModelMessage(ModelsService.java:181)
        at eu.nebulous.ems.boot.NebulousEventsService.processMessage(NebulousEventsService.java:158)
        at eu.nebulous.ems.boot.NebulousEventsService.lambda$startCommandProcessor$0(NebulousEventsService.java:127)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.lang.VirtualThread.run(Unknown Source)
Caused by: eu.nebulous.ems.translate.ModelException: Object is not a Map:
        ... 26 common frames omitted

2024-12-09T14:48:48.880Z ERROR 30 --- [heduling-709492] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.translateAppModel(): EXCEPTION: eu.nebulous.ems.translate.NebulousEmsTranslationException: Error while translating metric model file: a974662b-70be-43c2-bcda-02e93bc47db3--model--1733755728734.yml

eu.nebulous.ems.translate.NebulousEmsTranslationException: Error while translating metric model file: a974662b-70be-43c2-bcda-02e93bc47db3--model--1733755728734.yml
        at eu.nebulous.ems.translate.NebulousEmsTranslator.translate(NebulousEmsTranslator.java:108)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.translateAppModelAndStore(ControlServiceCoordinator.java:566)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator._translateAppModel(ControlServiceCoordinator.java:344)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.lambda$translateAppModel$2(ControlServiceCoordinator.java:233)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator._lockAndProcessModel(ControlServiceCoordinator.java:290)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator.translateAppModel(ControlServiceCoordinator.java:231)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
        at gr.iccs.imu.ems.control.controller.ControlServiceCoordinator$$SpringCGLIB$$0.translateAppModel(<generated>)
        at eu.nebulous.ems.translate.TranslationService.translateModel(TranslationService.java:52)
        at eu.nebulous.ems.boot.ModelsService.processMetricModelMessage(ModelsService.java:181)
        at eu.nebulous.ems.boot.NebulousEventsService.processMessage(NebulousEventsService.java:158)
        at eu.nebulous.ems.boot.NebulousEventsService.lambda$startCommandProcessor$0(NebulousEventsService.java:127)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.lang.VirtualThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: eu.nebulous.ems.translate.ModelException: Object is not a Map:
        at eu.nebulous.ems.translate.analyze.AnalysisUtils.createException(AnalysisUtils.java:52)
        at eu.nebulous.ems.translate.analyze.AnalysisUtils.asMap(AnalysisUtils.java:71)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.lambda$buildElementLists$12(MetricModelAnalyzer.java:311)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.lambda$buildElementLists$14(MetricModelAnalyzer.java:305)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.buildElementLists(MetricModelAnalyzer.java:287)
        at eu.nebulous.ems.translate.analyze.MetricModelAnalyzer.analyzeModel(MetricModelAnalyzer.java:113)
        at eu.nebulous.ems.translate.NebulousEmsTranslator.translate(NebulousEmsTranslator.java:207)
        at eu.nebulous.ems.translate.NebulousEmsTranslator.translate(NebulousEmsTranslator.java:102)
        ... 16 common frames omitted
Caused by: eu.nebulous.ems.translate.ModelException: Object is not a Map:
        ... 26 common frames omitted

```

**Comment by ipatini** [comment]
If it is a different metric model case, please attach (or send me) the offending metric model
